version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: kbank-redis
    ports:
      - "6400:6379"
    environment:
      REDIS_PASSWORD: kbank

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mysql:
    image: mysql:latest
    container_name: kbank-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kbank
    volumes:
      - ./mysql-data:/var/lib/mysql